# Generated by Django 2.1.11 on 2020-06-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('remark', models.TextField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(default='lixiaofeng', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
