# Generated by Django 3.0.7 on 2020-06-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_teamusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamusers',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teamusers',
            old_name='user_id',
            new_name='user',
        ),
    ]
