# Generated by Django 3.0.7 on 2020-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200619_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('Icon', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=6)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'modular',
            },
        ),
    ]
