# Generated by Django 3.0.7 on 2020-06-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_modulartable'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulartable',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Team'),
        ),
    ]
