# Generated by Django 3.0.7 on 2020-07-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200629_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project'),
        ),
    ]
